-- +migrate Up

-- ============================================================================
-- OWASP Amass: High-performance SCHEMA (PostgreSQL 13+)
-- - Native types: inet/cidr, citext
-- - Smallint lookup tables for entity/edge types
-- - Partitioned hot tables (edges, entity_tag_map, edge_tag_map)
-- - Targeted composite/partial indexes
-- ============================================================================

-- --- Extensions --------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- --- Lookup tables for compact type ids -------------------------------------
CREATE TABLE IF NOT EXISTS public.entity_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.edge_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tag_type_lu (
  id    smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name  text NOT NULL UNIQUE
);

INSERT INTO public.entity_type_lu(name) VALUES
  ('account'),('autnumrecord'),('autonomoussystem'),('contactrecord'),('domainrecord'),('file'),
  ('fqdn'),('fundstransfer'),('identifier'),('ipaddress'),('ipnetrecord'),('location'),('netblock'),
  ('organization'),('person'),('phone'),('product'),('productrelease'),('service'),('tlscertificate'),
  ('url')
ON CONFLICT DO NOTHING;

INSERT INTO public.edge_type_lu(name) VALUES
  ('basicdnsrelation'),('portrelation'),('prefdnsrelation'),('simplerelation'),('srvdnsrelation')
ON CONFLICT DO NOTHING;

INSERT INTO public.tag_type_lu(name) VALUES
  ('dnsrecordproperty'),('simpleproperty'),('sourceproperty'),('vulnproperty')
ON CONFLICT DO NOTHING;

-- -----------------------------
-- Core entity mapping
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.entity (
  entity_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT now(),
  updated_at    timestamp without time zone NOT NULL DEFAULT now(),
  etype_id      smallint  NOT NULL REFERENCES public.entity_type_lu(id),
  natural_key   citext    NOT NULL,       -- canonical display string
  table_name    citext    NOT NULL,       -- source table name
  row_id        bigint    NOT NULL,       -- source table row id
  UNIQUE (etype_id, row_id),
  UNIQUE (etype_id, natural_key),
  UNIQUE (table_name, row_id)
);
CREATE INDEX IF NOT EXISTS idx_entity_created_at ON public.entity (created_at);
CREATE INDEX IF NOT EXISTS idx_entity_updated_at ON public.entity (updated_at);
CREATE INDEX IF NOT EXISTS idx_entity_type ON public.entity (etype_id);
CREATE INDEX IF NOT EXISTS idx_entity_natural_key ON public.entity (natural_key);
CREATE INDEX IF NOT EXISTS idx_entity_table_name ON public.entity (table_name);
CREATE INDEX IF NOT EXISTS idx_entity_row_id ON public.entity (row_id);

-- -----------------------------
-- Graph edges
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.edge (
  edge_id        bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at     timestamp without time zone NOT NULL DEFAULT now(),
  updated_at     timestamp without time zone NOT NULL DEFAULT now(),
  etype_id       smallint    NOT NULL REFERENCES public.edge_type_lu(id),
  label          citext      NOT NULL,
  content        jsonb       NOT NULL DEFAULT '{}'::jsonb,
  from_entity_id bigint      NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  to_entity_id   bigint      NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  UNIQUE (etype_id, from_entity_id, to_entity_id, label),
  CHECK (from_entity_id <> to_entity_id)
);
CREATE INDEX IF NOT EXISTS idx_edge_created_at ON public.edge (created_at);
CREATE INDEX IF NOT EXISTS idx_edge_updated_at ON public.edge (updated_at);
CREATE INDEX IF NOT EXISTS idx_edge_etype ON public.edge (etype_id);
CREATE INDEX IF NOT EXISTS idx_edge_label ON public.edge (label);
CREATE INDEX IF NOT EXISTS gin_edge_content ON public.edge USING gin (content jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_edge_from_id ON public.edge (from_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_to_id   ON public.edge (to_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_from ON public.edge (from_entity_id, etype_id, to_entity_id);
CREATE INDEX IF NOT EXISTS idx_edge_to   ON public.edge (to_entity_id, etype_id, from_entity_id);


-- -----------------------------
-- Graph tags
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.tag (
  tag_id          bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at      timestamp without time zone NOT NULL DEFAULT now(),
  updated_at      timestamp without time zone NOT NULL DEFAULT now(),
  ttype_id        smallint NOT NULL REFERENCES public.tag_type_lu(id),
  property_name   TEXT NOT NULL,
  property_value  TEXT NOT NULL,
  content         jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (ttype_id, property_name, property_value)
);
CREATE INDEX IF NOT EXISTS idx_tag_created_at ON public.tag(created_at);
CREATE INDEX IF NOT EXISTS idx_tag_updated_at ON public.tag(updated_at);
CREATE INDEX IF NOT EXISTS idx_tag_ttype_id ON public.tag(ttype_id);
CREATE INDEX IF NOT EXISTS idx_tag_property_name ON public.tag(property_name);
CREATE INDEX IF NOT EXISTS idx_tag_tt_name ON public.tag(ttype_id, property_name);
CREATE INDEX IF NOT EXISTS idx_tag_property_name_value
  ON public.tag (property_name, property_value);
CREATE INDEX IF NOT EXISTS gin_tag_content ON public.tag USING gin (content jsonb_path_ops);

CREATE TABLE IF NOT EXISTS public.entity_tag_map (
  map_id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at     timestamp without time zone NOT NULL DEFAULT now(),
  updated_at     timestamp without time zone NOT NULL DEFAULT now(),
  entity_id      bigint NOT NULL REFERENCES public.entity(entity_id) ON DELETE CASCADE,
  tag_id         bigint NOT NULL REFERENCES public.tag(tag_id) ON DELETE CASCADE,
  UNIQUE (entity_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_entity_tag_map_created_at ON public.entity_tag_map(created_at);
CREATE INDEX IF NOT EXISTS idx_entity_tag_map_updated_at ON public.entity_tag_map(updated_at);
CREATE INDEX IF NOT EXISTS idx_entity_tag_map_entity_updated
  ON public.entity_tag_map (entity_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_entity_tag_map_entity_id ON public.entity_tag_map(entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_tag_map_tag_id ON public.entity_tag_map(tag_id);

CREATE TABLE IF NOT EXISTS public.edge_tag_map (
  map_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  edge_id    bigint NOT NULL REFERENCES public.edge(edge_id) ON DELETE CASCADE,
  tag_id     bigint NOT NULL REFERENCES public.tag(tag_id) ON DELETE CASCADE,
  UNIQUE (edge_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_edge_tag_map_created_at ON public.edge_tag_map(created_at);
CREATE INDEX IF NOT EXISTS idx_edge_tag_map_updated_at ON public.edge_tag_map(updated_at);
CREATE INDEX IF NOT EXISTS idx_edge_tag_map_edge_updated
  ON public.edge_tag_map (edge_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_edge_tag_map_edge_id ON public.edge_tag_map(edge_id);
CREATE INDEX IF NOT EXISTS idx_edge_tag_map_tag_id ON public.edge_tag_map(tag_id);


-- +migrate Down

DROP INDEX IF EXISTS idx_edge_tag_map_tag_id;
DROP INDEX IF EXISTS idx_edge_tag_map_edge_id;
DROP INDEX IF EXISTS idx_edge_tag_map_edge_updated;
DROP INDEX IF EXISTS idx_edge_tag_map_updated_at;
DROP INDEX IF EXISTS idx_edge_tag_map_created_at;
DROP TABLE IF EXISTS public.edge_tag_map;

DROP INDEX IF EXISTS idx_entity_tag_map_tag_id;
DROP INDEX IF EXISTS idx_entity_tag_map_entity_id;
DROP INDEX IF EXISTS idx_entity_tag_map_entity_updated;
DROP INDEX IF EXISTS idx_entity_tag_map_updated_at;
DROP INDEX IF EXISTS idx_entity_tag_map_created_at;
DROP TABLE IF EXISTS public.entity_tag_map;

DROP INDEX IF EXISTS gin_tag_content;
DROP INDEX IF EXISTS idx_tag_property_name_value;
DROP INDEX IF EXISTS idx_tag_tt_name;
DROP INDEX IF EXISTS idx_tag_property_name;
DROP INDEX IF EXISTS idx_tag_ttype_id;
DROP INDEX IF EXISTS idx_tag_updated_at;
DROP INDEX IF EXISTS idx_tag_created_at;
DROP TABLE IF EXISTS public.tag;

DROP INDEX IF EXISTS idx_edge_from;
DROP INDEX IF EXISTS idx_edge_to;
DROP INDEX IF EXISTS idx_edge_from_id;
DROP INDEX IF EXISTS idx_edge_to_id;
DROP INDEX IF EXISTS gin_edge_content;
DROP INDEX IF EXISTS idx_edge_label;
DROP INDEX IF EXISTS idx_edge_etype;
DROP INDEX IF EXISTS idx_edge_updated_at;
DROP INDEX IF EXISTS idx_edge_created_at;
DROP TABLE IF EXISTS public.edge;

DROP INDEX IF EXISTS idx_entity_row_id;
DROP INDEX IF EXISTS idx_entity_table_name;
DROP INDEX IF EXISTS idx_entity_natural_key;
DROP INDEX IF EXISTS idx_entity_type;
DROP INDEX IF EXISTS idx_entity_updated_at;
DROP INDEX IF EXISTS idx_entity_created_at;
DROP TABLE IF EXISTS public.entity;

DROP TABLE IF EXISTS public.tag_type_lu;
DROP TABLE IF EXISTS public.edge_type_lu;
DROP TABLE IF EXISTS public.entity_type_lu;

DROP EXTENSION IF EXISTS btree_gin;
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS citext;