-- +migrate Up

-- ============================================================================
-- OWASP Amass: High-performance SCHEMA (PostgreSQL 13+)
-- - Native types: inet/cidr, citext
-- - Smallint lookup tables for entity/edge types
-- - Partitioned hot tables (edges, entity_tag_map, edge_tag_map)
-- - Targeted composite/partial indexes
-- ============================================================================

BEGIN;

-- --- Extensions --------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS citext;

-- --- Lookup tables for compact type ids -------------------------------------
CREATE TABLE IF NOT EXISTS public.entity_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.edge_type_lu (
  id   smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);

-- Seed known entity types (add more as needed)
INSERT INTO public.entity_type_lu(name) VALUES
  ('account'),('autnumrecord'),('autonomoussystem'),('contactrecord'),
  ('domainrecord'),('file'),('fqdn'),('fundstransfer'),('identifier'),
  ('ipaddress'),('ipnetrecord'),('location'),('netblock'),('organization'),
  ('person'),('phone'),('product'),('productrelease'),('service'),
  ('tlscertificate'),('url')
ON CONFLICT DO NOTHING;

-- Optionally seed common edge types (examples)
INSERT INTO public.edge_type_lu(name) VALUES
  ('address'),('contact'),('release'),('manufacturer'),('provider'),('certificate'),('terms_of_service'),
  ('product_used'),('common_name'),('subject_contact'),('issuer_contact'),('san_dns_name'),('san_url'),
  ('san_ip_address'),('san_email_address'),('issuing_certificate'),('issuing_certificate_url'),('domain'),
  ('ocsp_server'),('ip_address'),('file'),('id'),('user'),('announces'),('registration'),('fqdn'),('url'),
  ('name_server'),('registrar_contact'),('registrant_contact'),('billing_contact'),('contains'),('node'),
  ('dns_record'),('port'),('verified_for'),('sender'),('recipient'),('third_party'),('issuing_agent'),
  ('registration_agency'),('issuing_authority'),('ptr_record'),('legal_address'),('hq_address'),('location'),
  ('subsidiary'),('org_unit'),('account'),('member'),('website'),('social_media_profile'),('funding_source'),
  ('registrant'),('rdap_url'),('abuse_contact'),('admin_contact'),('technical_contact'),('whois_server'),
  ('organization'),('person'),('phone')
ON CONFLICT DO NOTHING;

-- --- Core entity & mapping ---------------------------------------------------
CREATE TABLE IF NOT EXISTS public.entities (
  entity_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at    timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type_id       smallint NOT NULL REFERENCES public.entity_type_lu(id),
  display_value text NOT NULL,
  attrs         jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (type_id, display_value)
);
CREATE INDEX IF NOT EXISTS idx_entities_type ON public.entities(type_id);

CREATE TABLE IF NOT EXISTS public.entity_ref (
  ref_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entity_id  bigint NOT NULL REFERENCES public.entities(entity_id) ON DELETE CASCADE,
  table_name text NOT NULL,
  row_id     integer NOT NULL,
  UNIQUE (table_name, row_id),
  UNIQUE (entity_id, table_name, row_id)
);
CREATE INDEX IF NOT EXISTS idx_entity_ref_entity ON public.entity_ref(entity_id);
CREATE INDEX IF NOT EXISTS idx_entity_ref_table_row ON public.entity_ref(table_name, row_id);

-- --- Asset tables (native types where helpful) -------------------------------
CREATE TABLE IF NOT EXISTS public.account (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unique_id   text NOT NULL UNIQUE,
  account_type text NOT NULL,
  username    text,
  account_number text,
  balance numeric,
  active boolean
);

CREATE TABLE IF NOT EXISTS public.autnumrecord (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_name text,
  handle text NOT NULL UNIQUE,
  asn integer NOT NULL UNIQUE,
  record_status text,
  created_date timestamp without time zone,
  updated_date timestamp without time zone,
  whois_server text
);

CREATE TABLE IF NOT EXISTS public.autonomoussystem (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  asn integer NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.contactrecord (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  discovered_at text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.domainrecord (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unique_id  text,
  raw_record text,
  record_name text NOT NULL,
  domain citext NOT NULL UNIQUE,
  record_status text[],
  punycode text,
  extension text,
  created_date timestamp without time zone,
  updated_date timestamp without time zone,
  expiration_date timestamp without time zone,
  whois_server text
);
CREATE INDEX IF NOT EXISTS idx_domainrecord_record_name ON public.domainrecord(record_name);
CREATE INDEX IF NOT EXISTS idx_domainrecord_extension ON public.domainrecord(extension);

CREATE TABLE IF NOT EXISTS public.file (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  file_url text NOT NULL UNIQUE,
  basename text,
  file_type text
);

CREATE TABLE IF NOT EXISTS public.fqdn (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fqdn citext NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.fundstransfer (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unique_id text NOT NULL UNIQUE,
  amount numeric NOT NULL,
  reference_number text,
  currency text,
  transfer_method text,
  exchange_date timestamp without time zone,
  exchange_rate numeric
);

CREATE TABLE IF NOT EXISTS public.identifier (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_type text,
  unique_id text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.ipaddress (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_version text NOT NULL,
  ip_address inet NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.ipnetrecord (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  record_cidr cidr NOT NULL UNIQUE,
  record_name text NOT NULL,
  ip_version text NOT NULL,
  handle text NOT NULL UNIQUE,
  method text,
  record_status text[],
  created_date timestamp without time zone,
  updated_date timestamp without time zone,
  whois_server text,
  parent_handle text,
  start_address inet,
  end_address inet,
  country text
);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_record_name ON public.ipnetrecord(record_name);
CREATE INDEX IF NOT EXISTS idx_ipnetrecord_ip_version ON public.ipnetrecord(ip_version);

CREATE TABLE IF NOT EXISTS public.location (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  city text NOT NULL,
  unit text,
  street_address text NOT NULL UNIQUE,
  country text NOT NULL,
  building text,
  province text,
  locality text,
  postal_code text,
  street_name text,
  building_number text
);
CREATE INDEX IF NOT EXISTS idx_location_city ON public.location(city);
CREATE INDEX IF NOT EXISTS idx_location_country ON public.location(country);

CREATE TABLE IF NOT EXISTS public.netblock (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  netblock_cidr cidr NOT NULL UNIQUE,
  ip_version text
);

CREATE TABLE IF NOT EXISTS public.organization (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  org_name text,
  active boolean,
  unique_id text NOT NULL UNIQUE,
  legal_name text NOT NULL,
  jurisdiction text,
  founding_date timestamp without time zone,
  registration_id text
);
CREATE INDEX IF NOT EXISTS idx_organization_legal_name ON public.organization(legal_name);

CREATE TABLE IF NOT EXISTS public.person (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  full_name text,
  unique_id text NOT NULL UNIQUE,
  first_name text,
  family_name text,
  middle_name text
);
CREATE INDEX IF NOT EXISTS idx_person_full_name ON public.person(full_name);

CREATE TABLE IF NOT EXISTS public.phone (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_number text NOT NULL,
  e164 text NOT NULL UNIQUE,
  number_type text,
  country_code integer,
  country_abbrev text
);
CREATE INDEX IF NOT EXISTS idx_phone_raw ON public.phone(raw_number);

CREATE TABLE IF NOT EXISTS public.product (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unique_id text NOT NULL UNIQUE,
  product_name text NOT NULL,
  product_type text,
  category text,
  product_description text,
  country_of_origin text
);
CREATE INDEX IF NOT EXISTS idx_product_name ON public.product(product_name);

CREATE TABLE IF NOT EXISTS public.productrelease (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  release_name text NOT NULL UNIQUE,
  release_date timestamp without time zone
);
CREATE INDEX IF NOT EXISTS idx_productrelease_name ON public.productrelease(release_name);

CREATE TABLE IF NOT EXISTS public.service (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unique_id text NOT NULL UNIQUE,
  service_type text NOT NULL,
  output_data text,
  output_length integer,
  attributes jsonb
);
CREATE INDEX IF NOT EXISTS idx_service_service_type ON public.service(service_type);

CREATE TABLE IF NOT EXISTS public.tlscertificate (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_ca boolean,
  tls_version integer,
  key_usage text,
  not_after timestamp without time zone,
  not_before timestamp without time zone,
  ext_key_usage text,
  serial_number text NOT NULL UNIQUE,
  subject_key_id text,
  authority_key_id text,
  issuer_common_name text,
  signature_algorithm text,
  subject_common_name text NOT NULL,
  public_key_algorithm text,
  crl_distribution_points text
);
CREATE INDEX IF NOT EXISTS idx_tlscertificate_subject_common_name ON public.tlscertificate(subject_common_name);

CREATE TABLE IF NOT EXISTS public.url (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_url text NOT NULL UNIQUE,
  host citext NOT NULL,
  url_path text,
  port integer,
  scheme text
);
CREATE INDEX IF NOT EXISTS idx_url_host ON public.url(host);

-- --- Graph edges (partitioned) ----------------------------------------------
CREATE TABLE IF NOT EXISTS public.edges (
  edge_id      bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at   timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  etype_id     smallint NOT NULL REFERENCES public.edge_type_lu(id),
  content      jsonb NOT NULL DEFAULT '{}'::jsonb,
  from_entity_id bigint NOT NULL REFERENCES public.entities(entity_id) ON DELETE CASCADE,
  to_entity_id   bigint NOT NULL REFERENCES public.entities(entity_id) ON DELETE CASCADE,
  UNIQUE (etype_id, from_entity_id, to_entity_id),
  CHECK (from_entity_id <> to_entity_id)
) PARTITION BY HASH (from_entity_id);

DO $$
BEGIN
  FOR i IN 0..31 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.edges_p%1$s PARTITION OF public.edges FOR VALUES WITH (MODULUS 32, REMAINDER %1$s);', i
    );
  END LOOP;
END$$;

CREATE INDEX IF NOT EXISTS idx_edges_from_cover ON public.edges (from_entity_id, etype_id, to_entity_id) INCLUDE (created_at);
CREATE INDEX IF NOT EXISTS idx_edges_to_cover   ON public.edges (to_entity_id, etype_id, from_entity_id) INCLUDE (created_at);
-- JSON filtering only if needed:
-- CREATE INDEX IF NOT EXISTS idx_edges_content_jpath ON public.edges USING GIN (content jsonb_path_ops);

-- --- Tags (normalized dictionary + partitioned maps) ------------------------
CREATE TABLE IF NOT EXISTS public.tags (
  tag_id     bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  namespace  text DEFAULT 'default',
  name       text NOT NULL,
  value      text,
  meta       jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (namespace, name, COALESCE(value,'∅'))
);
CREATE INDEX IF NOT EXISTS idx_tags_namespace_name ON public.tags(namespace, name);

CREATE TABLE IF NOT EXISTS public.entity_tag_map (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entity_id  bigint NOT NULL REFERENCES public.entities(entity_id) ON DELETE CASCADE,
  tag_id     bigint NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
  details    jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (entity_id, tag_id)
) PARTITION BY HASH (entity_id);

DO $$
BEGIN
  FOR i IN 0..31 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.entity_tag_map_p%1$s PARTITION OF public.entity_tag_map FOR VALUES WITH (MODULUS 32, REMAINDER %1$s);', i
    );
  END LOOP;
END$$;

CREATE INDEX IF NOT EXISTS idx_entity_tag_map_entity ON public.entity_tag_map (entity_id, tag_id);

CREATE TABLE IF NOT EXISTS public.edge_tag_map (
  id         bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edge_id    bigint NOT NULL REFERENCES public.edges(edge_id) ON DELETE CASCADE,
  tag_id     bigint NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
  details    jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (edge_id, tag_id)
) PARTITION BY HASH (edge_id);

DO $$
BEGIN
  FOR i IN 0..31 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS public.edge_tag_map_p%1$s PARTITION OF public.edge_tag_map FOR VALUES WITH (MODULUS 32, REMAINDER %1$s);', i
    );
  END LOOP;
END$$;

CREATE INDEX IF NOT EXISTS idx_edge_tag_map_edge ON public.edge_tag_map (edge_id, tag_id);

-- --- Partial indexes for hottest entity lookups -----------------------------
DO $$
DECLARE
  tid_ip  smallint := (SELECT id FROM public.entity_type_lu WHERE name='ipaddress');
  tid_fq  smallint := (SELECT id FROM public.entity_type_lu WHERE name='fqdn');
  tid_org smallint := (SELECT id FROM public.entity_type_lu WHERE name='organization');
  tid_dom smallint := (SELECT id FROM public.entity_type_lu WHERE name='domainrecord');
  tid_url smallint := (SELECT id FROM public.entity_type_lu WHERE name='url');
BEGIN
  IF tid_ip IS NOT NULL THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_entities_ip ON public.entities(display_value) WHERE type_id = %s;', tid_ip);
  END IF;
  IF tid_fq IS NOT NULL THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_entities_fqdn ON public.entities(display_value) WHERE type_id = %s;', tid_fq);
  END IF;
  IF tid_org IS NOT NULL THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_entities_org ON public.entities(display_value) WHERE type_id = %s;', tid_org);
  END IF;
  IF tid_dom IS NOT NULL THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_entities_domain ON public.entities(display_value) WHERE type_id = %s;', tid_dom);
  END IF;
  IF tid_url IS NOT NULL THEN
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_entities_url ON public.entities(display_value) WHERE type_id = %s;', tid_url);
  END IF;
END$$;

COMMIT;

-- +migrate Down

DROP INDEX IF EXISTS idx_entities_url;
DROP INDEX IF EXISTS idx_entities_domain;
DROP INDEX IF EXISTS idx_entities_org;
DROP INDEX IF EXISTS idx_entities_fqdn;
DROP INDEX IF EXISTS idx_entities_ip;

DROP INDEX IF EXISTS idx_edge_tag_map_edge;
DROP TABLE IF EXISTS public.edge_tag_map;

DROP INDEX IF EXISTS idx_entity_tag_map_entity;
DROP TABLE IF EXISTS public.entity_tag_map;

DROP INDEX IF EXISTS idx_tags_namespace_name;
DROP TABLE IF EXISTS public.tags;

DROP INDEX IF EXISTS idx_edges_to_cover;
DROP INDEX IF EXISTS idx_edges_from_cover;
DROP TABLE IF EXISTS public.edges;

DROP INDEX IF EXISTS idx_url_host;
DROP TABLE IF EXISTS public.url;

DROP INDEX IF EXISTS idx_tlscertificate_subject_common_name;
DROP TABLE IF EXISTS public.tlscertificate;

DROP INDEX IF EXISTS idx_service_service_type;
DROP TABLE IF EXISTS public.service;

DROP INDEX IF EXISTS idx_productrelease_name;
DROP TABLE IF EXISTS public.productrelease;

DROP INDEX IF EXISTS idx_product_name;
DROP TABLE IF EXISTS public.product;

DROP INDEX IF EXISTS idx_phone_raw;
DROP TABLE IF EXISTS public.phone;

DROP INDEX IF EXISTS idx_person_full_name;
DROP TABLE IF EXISTS public.person;

DROP INDEX IF EXISTS idx_organization_legal_name;
DROP TABLE IF EXISTS public.organization;
DROP TABLE IF EXISTS public.netblock;

DROP INDEX IF EXISTS idx_location_country
DROP INDEX IF EXISTS idx_location_city;
DROP TABLE IF EXISTS public.location;

DROP INDEX IF EXISTS idx_ipnetrecord_ip_version;
DROP INDEX IF EXISTS idx_ipnetrecord_record_name;
DROP TABLE IF EXISTS public.ipnetrecord;

DROP TABLE IF EXISTS public.ipaddress;
DROP TABLE IF EXISTS public.identifier;
DROP TABLE IF EXISTS public.fundstransfer;
DROP TABLE IF EXISTS public.fqdn;
DROP TABLE IF EXISTS public.file;

DROP INDEX IF EXISTS idx_domainrecord_extension;
DROP INDEX IF EXISTS idx_domainrecord_record_name;
DROP TABLE IF EXISTS public.domainrecord;

DROP TABLE IF EXISTS public.contactrecord;
DROP TABLE IF EXISTS public.autonomoussystem;
DROP TABLE IF EXISTS public.autnumrecord;
DROP TABLE IF EXISTS public.account;

DROP INDEX IF EXISTS idx_entity_ref_table_row;
DROP INDEX IF EXISTS idx_entity_ref_entity;
DROP TABLE IF EXISTS public.entity_ref;

DROP INDEX IF EXISTS idx_entities_type;
DROP TABLE IF EXISTS public.entities;

DROP TABLE IF EXISTS public.edge_type_lu;
DROP TABLE IF EXISTS public.entity_type_lu;

DROP EXTENSION IF EXISTS citext;