name: ci

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: develop

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m

  unit:
    name: unit
    runs-on: ubuntu-20.04
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SQLITE3_DB: test.db
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Setup PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        id: postgres
      - run: |
          go test -race -timeout 240s ./...
